- name: Install Nginx and websites
  hosts: webservers
  become: yes
  become_user: root

  tasks:
    - name: Update APT Package Cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nginx

    - name: Configure Nginx Document Root
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify:
        - Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
