name: CI for Our Website
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build HTML
      run: |
        echo "Static site doesn't need to be built."

    - name: Test HTML
      run: |
        # Add test coverage here later

    - name: Deploy to staging


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa ${{ secrets.EC2_INSTANCE_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_INSTANCE_IP }} 'bash -s' < deploy-script.sh


  performance_test:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '14'

    - name: Run JMeter Tests
      run: |
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.tgz
        tar -xf apache-jmeter-5.4.1.tgz
        export PATH=$PATH:$PWD/apache-jmeter-5.4.1/bin
        jmeter -n -t ./test_plan.jmx -l test_results.jtl

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: test_results.jtl
